### ISSUE TITLE
log4j default logging level for sparkmonitor

### ISSUE THREAD

**Issue by berglh** [swan-cern/sparkmonitor#24]
Hi there,

Currently, when we are configuring logging in Spark 3.3.2 with JupyterLab 3.6.5, we are using the log4j2.properties file to set the logging the level for pyspark notebooks (iPython).

When we use `sparkmonitor` we receive the following INFO messages, which appear as red warning level message:
```
INFO:SparkMonitorKernel:Client Connected ('127.0.0.1', 47646)
```

Looking into the source code for the [listener](https://github.com/swan-cern/sparkmonitor/blob/master/scalalistener/CustomListener.scala#L36), I could see the class path should be something like JupyterSparkMonitorListener, which means in the pyspark log4j2 properties file, we would expect something like this:
```properties
logger.sparkmonitor.name = sparkmonitor.listener.JupyterSparkMonitorListener
logger.sparkmonitor.level = error
```

However, this didn't seem to work. Looking into the JupyterSparkMonitorListener class, I could see it was using log4j,not log4j2. I then tried including a log4j.properties file in the spark configuration directory using the old configuration format:

```properties
log4j.logger.sparkmonitor.listener.JupyterSparkMonitorListener=WARN
```
However, this didn't work either. Do you have any advice on how to adjust the log4j default logging level. We want to hide info level message from users in Jupyter Lab running Spark - not sure where or how to configure this.

**Comment by CarterFendley** [comment]
@berglh I believe what you are seeing if from the python Jupyter notebook extension, see logger initialization [here](https://github.com/swan-cern/sparkmonitor/blob/7b1cb8e9dfd9677d4e0441538f1c227964ebbb68/sparkmonitor/kernelextension.py#L157-L160) and the log statement you show [here](https://github.com/swan-cern/sparkmonitor/blob/7b1cb8e9dfd9677d4e0441538f1c227964ebbb68/sparkmonitor/kernelextension.py#L112).

You can disable this with the following python:
```python
import logging

logging.getLogger('tornado.sparkmonitor.kernel').setLevel(logging.WARNING)
```

Thanks for opening this issue though! Your comment helped my to figure out how to disable sparkmonitor's somewhat excessive Scala logging.

Scala 🤝 Python

**Comment by berglh** [comment]
@CarterFendley I appreciate you getting around to looking at this one :pray:  I'll investigate on my side and perhaps try setting up a iPython start-up script in the Jupyter Lab environment and report back. If this is the case, perhaps we should add some documentation about this control for users who care about it. I hadn't considered it was using Python logging, I was thinking it could have been further up in the UI stack with the Jupyter Lab plugin without digging into the source myself.

**Comment by berglh** [comment]
Hi @CarterFendley,

I did end up testing this in the Jupyter Lab 3.6.5 with Apache Spark 3.4.0. At the top of the of the ipython configuration file, I added the logging imports as suggested and this set the default logging level for SparkMonitor so that we only see warnings or errors.

```
vim ~/.ipython/profile_default/ipython_config.py 
```

```python
# Configuration file for ipython.

c = get_config()  #noqa

# Configure default logging level for sparkmonitor in Python notebooks.
c.InteractiveShellApp.exec_lines = [
    'import logging\n'
    'logging.getLogger("tornado.sparkmonitor.kernel").setLevel(logging.WARNING)'
]
```

I'm happy to call this specific issue as resolved, but up to you if you'd like to add README section for this.

**Comment by CarterFendley** [comment]
@berglh Cool stuff 👍 

I am not a maintainer of this project, but I would agree a mention in the README would be nice. A default not to log also seems like a good approach.
